# Project information
site_name: MDNC Documentation
site_description: The tutorial and API reference for the Modern Deep Network Toolkits for pyTorch (MDNC) which is a pyTorch framework for simplifying the data IO, visualization, and construction of deep-learning projects.
site_author: Yuchen Jin (cainmagi)
site_url: https://cainmagi.github.io/MDNC/

# Repository
repo_name: cainmagi/MDNC
repo_url: https://github.com/cainmagi/MDNC
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2021 Yuchen Jin'

# Configuration
theme:
  name: null
  custom_dir: material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Font, palette and git icon changed
  language: en
  features:
    #- navigation.instant
    - navigation.tabs
    - navigation.expand
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    scheme: default
    primary: red
    accent: deep orange
  font:
    text: Noto Sans
    code: Roboto Mono
  favicon: assets/icons/logo.png
  logo: assets/icons/logo.svg

plugins:
  - git-revision-date-localized
  - macros
  - search

# Customization
extra:
  disqus: 'mdnc-documentation'
  social:
    - icon: fontawesome/solid/globe
      link: https://cainmagi.github.io/
    - icon: fontawesome/solid/envelope
      link: mailto:cainmagi@gmail.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cainmagi
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/cainmagi
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/5885093621
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCzqpNK5qFMy5_cI1i0Z1nQw
    - icon: fontawesome/solid/music
      link: https://music.163.com/#/user/home?id=276304206

extra_css:
  - 'assets/stylesheets/custom.css'
  - 'assets/stylesheets/extensions.css'
  - 'assets/stylesheets/simpleLightbox.min.css'
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.1/mermaid.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'
  - 'assets/javascripts/simpleLightbox.min.js'
  - 'assets/javascripts/extensions.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.1.2/es5/tex-mml-chtml.min.js'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite:
      custom_inline:
        - { name: math, class: arithmatex, format: !!python/name:pymdownx.arithmatex.inline_mathjax_format }
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - { name: mermaid, class: mermaid, format: !!python/name:pymdownx.superfences.fence_div_format }
        - { name: math, class: overflow, format: !!python/name:pymdownx.superfences.fence_div_format }
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Tutorial:
    - Overview: index.md
    - Installation: installation.md
    - Licenses: licenses.md
  - APIs:
    - Overview: apis/overview.md
    - contribs:
      - torchsummary:
        - summary: apis/contribs/torchsummary/summary.md
        - summary_string: apis/contribs/torchsummary/summary_string.md
    - data:
      - h5py:
        - H5Converter: apis/data/h5py/H5Converter.md
        - H5SeqConverter: apis/data/h5py/H5SeqConverter.md
        - H5SupSaver: apis/data/h5py/H5SupSaver.md

# Google Analytics
google_analytics_4:
  - G-PDY947X8DD
