# Project information
site_name: MDNC Documentation
site_description: The tutorial and API reference for the Modern Deep Network Toolkits for pyTorch (MDNC) which is a pyTorch framework for simplifying the data IO, visualization, and construction of deep-learning projects.
site_author: Yuchen Jin (cainmagi)
site_url: https://cainmagi.github.io/MDNC/

# Repository
repo_name: cainmagi/MDNC
repo_url: https://github.com/cainmagi/MDNC
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2021 cainmagi@github (Yuchen Jin)'

# Configuration
theme:
  name: null
  custom_dir: material/material

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Font, palette and git icon changed
  language: en
  features:
    #- navigation.instant
    - navigation.tabs
    # - navigation.expand
  icon:
    repo: fontawesome/brands/git-alt
    logo: mdnc/logo
  palette:
    scheme: default
    primary: red
    accent: deep orange
  font:
    text: Noto Sans
    code: Roboto Mono
  favicon: assets/icons/logo.png

plugins:
  - git-revision-date-localized
  - macros
  - search
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
      js_files:
        - assets/javascripts/extensions.js

# Customization
extra:
  source:
    root: https://github.com/cainmagi/MDNC/blob/4b8cb65e677f4777e46bc91dc94316cb69ee8cad/mdnc
    version: 0.1.5
    progress: 15
  disqus: 'mdnc-documentation'
  social:
    - icon: fontawesome/solid/globe
      link: https://cainmagi.github.io/
    - icon: fontawesome/solid/envelope
      link: mailto:cainmagi@gmail.com
    - icon: fontawesome/brands/github-alt
      link: https://github.com/cainmagi
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/cainmagi
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/u/5885093621
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCzqpNK5qFMy5_cI1i0Z1nQw
    - icon: fontawesome/solid/music
      link: https://music.163.com/#/user/home?id=276304206

extra_css:
  - 'assets/stylesheets/extra.css'
  - 'assets/stylesheets/simpleLightbox.min.css'
  
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mermaid/8.9.1/mermaid.min.js'
  - 'assets/javascripts/simpleLightbox.min.js'
  - 'assets/javascripts/extensions.js'

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - custom/.icons
  - pymdownx.inlinehilite:
      custom_inline:
        - { name: math, class: arithmatex, format: !!python/name:pymdownx.arithmatex.inline_mathjax_format }
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      user: cainmagi
      repo: MDNC
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - { name: mermaid, class: "mermaid-container", format: !!python/name:pymdownx.superfences.fence_code_format }
        - { name: math, class: arithmatex, format: !!python/name:pymdownx.superfences.fence_div_format }
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true

# Page tree
nav:
  - Tutorial:
    - Overview: index.md
    - Installation: installation.md
    - Licenses: licenses.md
  - APIs:
    - Overview: apis/overview.md
    - "<span class='magic-codeicon-package'>contribs</span>":
      - "<span class='magic-codeicon-module'>torchsummary</span>":
        - "<span class='magic-codeicon-function'>summary</span>": apis/contribs/torchsummary/summary.md
        - "<span class='magic-codeicon-function'>summary_string</span>": apis/contribs/torchsummary/summary_string.md
    - "<span class='magic-codeicon-package'>data</span>":
      - "<span class='magic-codeicon-module'>h5py</span>":
        - "<span class='magic-codeicon-class'>H5Converter</span>": apis/data/h5py/H5Converter.md
        - "<span class='magic-codeicon-class'>H5SeqConverter</span>": apis/data/h5py/H5SeqConverter.md
        - "<span class='magic-codeicon-class'>H5SupSaver</span>": apis/data/h5py/H5SupSaver.md
        - "<span class='magic-codeicon-class'>H5GParser</span>": apis/data/h5py/H5GParser.md
        - "<span class='magic-codeicon-class'>H5CParser</span>": apis/data/h5py/H5CParser.md
        - "<span class='magic-codeicon-class'>H5RParser</span>": apis/data/h5py/H5RParser.md
      - "<span class='magic-codeicon-module'>sequence</span>":
        - "<span class='magic-codeicon-class'>MSequence</span>": apis/data/sequence/MSequence.md
        - "<span class='magic-codeicon-class'>MPSequence</span>": apis/data/sequence/MPSequence.md
        - "<span class='magic-codeicon-class'>MTSequence</span>": apis/data/sequence/MTSequence.md
      - "<span class='magic-codeicon-module'>preprocs</span>":
        - "<span class='magic-codeicon-class'>ProcAbstract</span>": apis/data/preprocs/ProcAbstract.md
        - "<span class='magic-codeicon-class'>ProcMerge</span>": apis/data/preprocs/ProcMerge.md
        - "<span class='magic-codeicon-class'>ProcScaler</span>": apis/data/preprocs/ProcScaler.md
        - "<span class='magic-codeicon-class'>ProcNSTScaler</span>": apis/data/preprocs/ProcNSTScaler.md
        - "<span class='magic-codeicon-class'>ProcFilter1d</span>": apis/data/preprocs/ProcFilter1d.md
        - "<span class='magic-codeicon-class'>ProcNSTFilter1d</span>": apis/data/preprocs/ProcNSTFilter1d.md
        - "<span class='magic-codeicon-class'>ProcPad</span>": apis/data/preprocs/ProcPad.md
        - "<span class='magic-codeicon-class'>ProcLifter</span>": apis/data/preprocs/ProcLifter.md
      - "<span class='magic-codeicon-module'>webtools</span>":
        - "<span class='magic-codeicon-function'>get_token</span>": apis/data/webtools/get_token.md
        - "<span class='magic-codeicon-function'>download_tarball_link</span>": apis/data/webtools/download_tarball_link.md
        - "<span class='magic-codeicon-function'>download_tarball</span>": apis/data/webtools/download_tarball.md
        - "<span class='magic-codeicon-function'>download_tarball_public</span>": apis/data/webtools/download_tarball_public.md
        - "<span class='magic-codeicon-function'>download_tarball_private</span>": apis/data/webtools/download_tarball_private.md
        - "<span class='magic-codeicon-class'>DataChecker</span>": apis/data/webtools/DataChecker.md
    - "<span class='magic-codeicon-package'>modules</span>":
      - "<span class='magic-codeicon-module'>conv</span>":
        - "<span class='magic-codeicon-class'>ConvModern1d</span>": apis/modules/conv/ConvModern1d.md
        - "<span class='magic-codeicon-class'>ConvModern2d</span>": apis/modules/conv/ConvModern2d.md
        - "<span class='magic-codeicon-class'>ConvModern3d</span>": apis/modules/conv/ConvModern3d.md
        - "<span class='magic-codeicon-class'>UNet1d</span>": apis/modules/conv/UNet1d.md
        - "<span class='magic-codeicon-class'>UNet2d</span>": apis/modules/conv/UNet2d.md
        - "<span class='magic-codeicon-class'>UNet3d</span>": apis/modules/conv/UNet3d.md
        - "<span class='magic-codeicon-class'>AE1d</span>": apis/modules/conv/AE1d.md
        - "<span class='magic-codeicon-class'>AE2d</span>": apis/modules/conv/AE2d.md
        - "<span class='magic-codeicon-class'>AE3d</span>": apis/modules/conv/AE3d.md
        - "<span class='magic-codeicon-class'>EncoderNet1d</span>": apis/modules/conv/EncoderNet1d.md
        - "<span class='magic-codeicon-class'>EncoderNet2d</span>": apis/modules/conv/EncoderNet2d.md
        - "<span class='magic-codeicon-class'>EncoderNet3d</span>": apis/modules/conv/EncoderNet3d.md
        - "<span class='magic-codeicon-class'>DecoderNet1d</span>": apis/modules/conv/DecoderNet1d.md
        - "<span class='magic-codeicon-class'>DecoderNet2d</span>": apis/modules/conv/DecoderNet2d.md
        - "<span class='magic-codeicon-class'>DecoderNet3d</span>": apis/modules/conv/DecoderNet3d.md
        - "<span class='magic-codeicon-function'>unet*</span>": apis/modules/conv/unetstar.md
        - "<span class='magic-codeicon-function'>ae*</span>": apis/modules/conv/aestar.md
        - "<span class='magic-codeicon-function'>encnet*</span>": apis/modules/conv/encnetstar.md
        - "<span class='magic-codeicon-function'>decnet*</span>": apis/modules/conv/decnetstar.md
      - "<span class='magic-codeicon-module'>resnet</span>":
        - "<span class='magic-codeicon-class'>BlockPlain1d</span>": apis/modules/resnet/BlockPlain1d.md
        - "<span class='magic-codeicon-class'>BlockPlain2d</span>": apis/modules/resnet/BlockPlain2d.md
        - "<span class='magic-codeicon-class'>BlockPlain3d</span>": apis/modules/resnet/BlockPlain3d.md
        - "<span class='magic-codeicon-class'>BlockBottleneck1d</span>": apis/modules/resnet/BlockBottleneck1d.md
        - "<span class='magic-codeicon-class'>BlockBottleneck2d</span>": apis/modules/resnet/BlockBottleneck2d.md
        - "<span class='magic-codeicon-class'>BlockBottleneck3d</span>": apis/modules/resnet/BlockBottleneck3d.md
        - "<span class='magic-codeicon-class'>UNet1d</span>": apis/modules/resnet/UNet1d.md
        - "<span class='magic-codeicon-class'>UNet2d</span>": apis/modules/resnet/UNet2d.md
        - "<span class='magic-codeicon-class'>UNet3d</span>": apis/modules/resnet/UNet3d.md
        - "<span class='magic-codeicon-class'>AE1d</span>": apis/modules/resnet/AE1d.md
        - "<span class='magic-codeicon-class'>AE2d</span>": apis/modules/resnet/AE2d.md
        - "<span class='magic-codeicon-class'>AE3d</span>": apis/modules/resnet/AE3d.md
        - "<span class='magic-codeicon-class'>EncoderNet1d</span>": apis/modules/resnet/EncoderNet1d.md
        - "<span class='magic-codeicon-class'>EncoderNet2d</span>": apis/modules/resnet/EncoderNet2d.md
        - "<span class='magic-codeicon-class'>EncoderNet3d</span>": apis/modules/resnet/EncoderNet3d.md
        - "<span class='magic-codeicon-class'>DecoderNet1d</span>": apis/modules/resnet/DecoderNet1d.md
        - "<span class='magic-codeicon-class'>DecoderNet2d</span>": apis/modules/resnet/DecoderNet2d.md
        - "<span class='magic-codeicon-class'>DecoderNet3d</span>": apis/modules/resnet/DecoderNet3d.md
        - "<span class='magic-codeicon-function'>unet*</span>": apis/modules/resnet/unetstar.md
        - "<span class='magic-codeicon-function'>ae*</span>": apis/modules/resnet/aestar.md
        - "<span class='magic-codeicon-function'>encnet*</span>": apis/modules/resnet/encnetstar.md
        - "<span class='magic-codeicon-function'>decnet*</span>": apis/modules/resnet/decnetstar.md
    - "<span class='magic-codeicon-package'>utils</span>":
      - "<span class='magic-codeicon-module'>draw</span>":
        - "<span class='magic-codeicon-class'>setFigure</span>": apis/utils/draw/setFigure.md
        - "<span class='magic-codeicon-function'>use_tex</span>": apis/utils/draw/use_tex.md
        - "<span class='magic-codeicon-function'>fix_log_axis</span>": apis/utils/draw/fix_log_axis.md
        - "<span class='magic-codeicon-class'>AxisMultipleTicker</span>": apis/utils/draw/AxisMultipleTicker.md
        - "<span class='magic-codeicon-function'>plot_hist</span>": apis/utils/draw/plot_hist.md
        - "<span class='magic-codeicon-function'>plot_bar</span>": apis/utils/draw/plot_bar.md
        - "<span class='magic-codeicon-function'>plot_scatter</span>": apis/utils/draw/plot_scatter.md
        - "<span class='magic-codeicon-function'>plot_training_records</span>": apis/utils/draw/plot_training_records.md
        - "<span class='magic-codeicon-function'>plot_error_curves</span>": apis/utils/draw/plot_error_curves.md
        - "<span class='magic-codeicon-function'>plot_distribution_curves</span>": apis/utils/draw/plot_distribution_curves.md
      - "<span class='magic-codeicon-module'>tools</span>":
        - "<span class='magic-codeicon-class'>EpochMetrics</span>": apis/utils/tools/EpochMetrics.md
        - "<span class='magic-codeicon-class'>ContextWrapper</span>": apis/utils/tools/ContextWrapper.md

# Google Analytics
google_analytics_4:
  - G-PDY947X8DD
